---
title: "Syllabus"
---


## Course info

|                   | Day       | Time                  | Location    |
|--        |--|-    |-|
| Seminar          | 10.11.23   | 09:00  - 17:00    |  Room S202  |
| Seminar          | 11.11.23   | 09:00  - 17:00    |  Room S202  |
| Online           | 12.11.23-10.01.24   |      |    |
| Seminar          | 11.01.24   | 09:00  - 17:00    |  Room S303  |

<br>

- [Applied Statistics Moodle-Course](https://moodle.hdm-stuttgart.de/course/view.php?id=16202)

<br>


## Course topics

Gain experience in data collection, exploratory data analysis, predictive modeling, statistical inference and Bayesian statistics while working on problems and case studies inspired by and based on real-world questions. 

Topics we will cover:

- Data & Study Design
- Exploratory data analysis
- Linear regression models
- Model selection methods
- Classification and logistic regression
- Statistical inference
- Probability and Bayes
- Data Storytelling
- Generative AI

The course will focus on the Python programming language.


## Learning objectives

By the end of the semester, you will be able to...

-   obtain, explore, visualize, and analyze data in Python to investigate patterns.
-   fit and evaluate regression and classification models to make predictions.
-   use resampling methods to obtain reliable predictions.
-   use statistical methods to test hypothesis.
-   apply Bayes' theorem, the foundation of Bayesian statistics. 
 


## Where to get help

- If you have a question during lecture, feel free to ask it! 
- Outside of class, any general questions about course content or assignments should be posted on the [Moodle course forum](https://moodle.hdm-stuttgart.de/mod/forum/view.php?id=303113).
- Emails should be reserved for questions not appropriate for the public forum. **If you email me, please include the name of our course in the subject line.** 

Check out the [Support](course-support.md) page for more resources.



## Textbooks

Main textbooks for the course:

- [Introduction to Modern Statistics (Version date: April 19, 2023)](https://openintro-ims.netlify.app/) by Mine Çetinkaya-Rundel and Johanna Hardin.

- [An Introduction to Statistical Learning with Applications in Python (2023)](https://www.statlearning.com/) by Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani and Jonathan Taylor.


- [Feature Engineering and Selection: A Practical Approach for Predictive Models (2019)](http://www.feat.engineering/index.html) by Max Kuhn and Kjell Johnson

Optional:

- Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow (2022, 3rd Edition) by Aurélien Géron.



## Lectures

A lot of what you do in this course will involve writing code, and coding is a skill that is best learned by doing.
Therefore, as much as possible, you will be working on a variety of tasks and activities throughout each lecture.

You are expected to bring a laptop to each class so that you can take part in the in-class exercises.



## Assessment

Assessment for the course is comprised of these components: 

- Application exercises 
- Exams in Moodle
- Project



### Application exercises

Parts of some lectures will be dedicated to working on "Application Exercises" (AE). These small exercises will be provided in GitHub Classroom and will give you an opportunity to apply the concepts and code introduced in the lectures.  

AEs should be completed individually.


### Exams in Moodle

There will be multiple open-note exams in Moodle. Through these exams you have the opportunity to demonstrate what you've learned in the course thus far.


:::{Note}
The exams will focus on the conceptual understanding of the content
:::

More details about the exams will be given in the seminar.


### Project

The purpose of the [project](project-description.md) is to apply what you've learned throughout the semester to analyze an interesting, data-driven research question. The project will be completed in **teams**.

More information about the project will be provided in the seminar.


## Grading


The final course grade will be calculated as follows:

| Category              | Percentage      |
|--|--|
| Application exercises | 15             |
| Exams                 | 35             |
| Project               | 50             |

The final grade will be determined based on the following thresholds:

|  Grade       | Percentage |
|--|--|
| 1.0           | 96 - 100          |
| 1.3           | 91 - 95           |
| 1.7           | 85 - 90           |
| 2.0           | 80 - 84           |
| 2.3           | 75 - 79           |
| 2.7           | 70 - 74           |
| 3.0           | 65 - 69           |
| 3.3           | 60 - 64           |
| 3.7           | 55 - 59           |
| 4.0            | 50 - 54          |
| 4.7           | 15 - 49           |
| 5.0            | 0 - 14           |



