---
title: "Data Storytelling"
---

The following content teaches you the fundamentals of data visualization and how to communicate effectively with data using Python. With visual elements like charts, graphs, and maps, data visualization tools provide an accessible way to see and understand trends, outliers, and patterns in data.


The slides are mainly based on the following resources:

*Available as E-Books in the [HdM library](https://www.hdm-stuttgart.de/bibliothek/angebot/eBooks):*

- "Storytelling with Data: A Data Visualization Guide for Business Professionals" by Cole Nussbaumer Knaflic. 

- "Storytelling mit Daten: Die Grundlagen der effektiven Kommunikation und Visualisierung mit Daten" von Cole Nussbaumer Knaflic.

- "Storytelling with Data : Let's Practice!" by Cole Nussbaumer Knaflic. 





|	Nr.	|	Topic	|	Literature	|		Slides		|
|	---	|	---	|	---	|		---		|
|	1	|	Data storytelling	|		|		[📑](https://docs.google.com/presentation/d/1irnXZ4O9d3xVypWxOkViNmUzqr5Q1dVRuxi17VAmKaM/export/pdf)		|
|	2	|	The importance of context	|		|		[📑](https://docs.google.com/presentation/d/1XXsxfPoo2kCCnR8FZ6Bs4CGpfx81_vck-VY2C7meEOM/export/pdf)		|
|	3	|	Pet shelter case study	|		|		[📑](https://docs.google.com/presentation/d/1L-QNkIez3WQ6jt4lwUv_Sf-UokwwlgL3Og5drO5Vs18/export/pdf)		|
|	4	|	Back to school sale case study	|		|		[📑](https://docs.google.com/presentation/d/1_jGHyu0aKsQk7jxOmHgscreCrfcqrp9WbQdtWyg087o/export/pdf)		|
|	5	|	Big idea worksheet	|		|		[📑](https://docs.google.com/document/d/1-GZvhdbhLYLB_Bo1arj1rgTqbJ5SUoU21vtgbYEhVqk/edit?usp=sharing)		|
|	6	|	Narrow your audience	|		|		[📑](https://docs.google.com/document/d/1Eu21TCIM0Lx6LiybPG-15ikk0gkRaqbCQNtcl3fAfGQ/edit?usp=sharing)		|
|	7	|	Storyboard 1	|		|		[📑](https://docs.google.com/document/d/1cuiBZiWaUkhAYNkQo6SWtWm8n_Q1IJt54lw0Na2-0DE/edit?usp=sharing)		|
|	8	|	Storyboard 2	|		|		[📑](https://docs.google.com/document/d/1WeLzE85YfM-F9-vAIhEbeJHkuHsN3xtovzIokB93BRU/edit?usp=sharing)		|
|	9	|	Choose an appropriate display	|		|		[📑](https://docs.google.com/presentation/d/1-uFVcFI7Y1ShyToEzahbg0VlkLnyn7A5Dq7NaHrZmU0/export/pdf)		|
|	10	|	Eliminate clutter	|		|		[📑](https://docs.google.com/presentation/d/1ixTCCx1xylQveXPwcV3g19fa_ZyXRJYXl69yG6kG7CE/export/pdf)		|
|	11	|	Focus attention	|		|		[📑](https://docs.google.com/presentation/d/1rwyx33EkV7ioIKee_d6ng6Sobi3eg1EFh2q36Yvx6Gc/export/pdf)		|
|	12	|	Think like a designer	|		|		[📑](https://docs.google.com/presentation/d/1HT-LiV_BhbVw6pTa2JGZOndPakdfCsqDSC4nWSGAf8w/export/pdf)		|
|	13	|	Exercises	|		|		[📑](https://docs.google.com/presentation/d/1Fz3v1euhIoyZgvP71LmhWwvWdTTDfAK1i_-yuWl-Zfc/export/pdf)		|
|	14	|	Tell a Story	|		|		[📑](https://docs.google.com/presentation/d/1L5GKC1UsWhMMCqs4ULA4jo7VZlrFInDn1dWif0KYRds/export/pdf)		|
|	15	|	How to deliver a presentation	|		|		[📑](https://docs.google.com/presentation/d/1ebeDWDk-ytY9qGx2peBLFyoSxTh3EezvN-jzW6Fe7dM/export/pdf)		|
|	16	|	Reporting with Quarto	|		|		[📑](https://docs.google.com/presentation/d/NA/export/pdf)		|
|	17	|	Streamlit dashboard	|		|		[📑](https://docs.google.com/presentation/d/NA/export/pdf)		|